"""EnterpriseIQ public demo: the Hugging Face Space entry point.

A Gradio Space runs `python app.py`. This file:

1. sets demo-safe defaults (Space secrets override any of them),
2. starts Postgres inside the Space (see start_embedded_postgres),
3. prepares the database: migrations, demo users, and corpus ingestion,
4. serves the FastAPI app (API and /docs) with a small Gradio UI mounted at
   /demo, on the one port the Space exposes.

The UI is layout only. What its buttons do lives in backend/app/web/demo_ui.py,
where it is tested in CI. Do not edit this file on Hugging Face: the GitHub
deploy workflow overwrites the Space on every push.
"""

# No `from __future__ import annotations` here: Gradio finds which handler
# argument should receive the request by reading its `gr.Request` annotation,
# and a string annotation naming a locally imported module cannot be resolved.

# Free Gradio Spaces run on ZeroGPU, which refuses to start an app that has no
# @spaces.GPU function ("No @spaces.GPU function detected during startup").
# This app never uses a GPU, so it declares one placeholder that is never
# called. `spaces` must be imported before anything imports torch. Off
# Hugging Face the decorator is a no-op.
import spaces


@spaces.GPU
def _zerogpu_placeholder() -> None:
    """Never called; satisfies ZeroGPU's startup check."""


def _report_zerogpu_startup() -> None:
    """Send ZeroGPU's startup report, which normally rides on Blocks.launch().

    `spaces` hooks gr.Blocks.launch() to report the app's @spaces.GPU
    functions to the platform. This app serves Gradio through uvicorn (so the
    API and the page share one server) and never calls launch(), so without
    this the platform sees no report and stops the Space with "No @spaces.GPU
    function detected during startup". spaces.zero.startup is the function
    that hook runs; it exists only on ZeroGPU hardware.
    """
    try:
        from spaces import zero
    except ImportError:
        return
    startup = getattr(zero, "startup", None)
    if startup is not None:
        startup()


_report_zerogpu_startup()


import os  # noqa: E402
import subprocess  # noqa: E402
import sys  # noqa: E402
import time  # noqa: E402
from pathlib import Path  # noqa: E402

ROOT = Path(__file__).resolve().parent
BACKEND = ROOT / "backend"

DEFAULTS = {
    "ENVIRONMENT": "production",
    "LOG_FORMAT": "json",
    "DEMO_MODE": "true",
    "AUTH_DEV_HEADER_ENABLED": "false",
    # Spaces sit behind one proxy, which appends the visitor's address.
    "FORWARDED_PROXY_HOPS": "1",
    "CORPUS_DIR": str(ROOT / "corpus"),
    "DEMO_UI_PATH": "/demo",
    "SEED_ON_STARTUP": "true",
    "EMBEDDED_POSTGRES": "true",
}
for key, value in DEFAULTS.items():
    os.environ.setdefault(key, value)

sys.path.insert(0, str(BACKEND))


def _run(*args: str, attempts: int = 1) -> None:
    """Run a backend script, retrying while a sleeping database wakes up."""
    for attempt in range(1, attempts + 1):
        result = subprocess.run([sys.executable, *args], cwd=BACKEND, check=False)
        if result.returncode == 0:
            return
        if attempt < attempts:
            print(f"[startup] {' '.join(args)} failed, retrying ({attempt}/{attempts})", flush=True)
            time.sleep(5)
    raise SystemExit(f"[startup] {' '.join(args)} failed; see the logs above")


def start_embedded_postgres():  # type: ignore[no-untyped-def]
    """Run Postgres (with pgvector) inside the Space, from the pgserver wheel.

    Free Spaces could not reach an external database: connections to Supabase
    on 5432 timed out at startup. An embedded server needs no network and no
    account. The trade-off is that its data lives on the Space's disk, which
    is wiped on restart, so every start rebuilds it: migrations, demo users
    and corpus ingestion all run again, and the audit trail starts empty.
    Set EMBEDDED_POSTGRES=false and the POSTGRES_* secrets to use an external
    database instead.
    """
    if os.environ.get("EMBEDDED_POSTGRES", "true").lower() != "true":
        return None
    import pgserver

    data_dir = Path(os.environ.get("EMBEDDED_POSTGRES_DIR", str(ROOT / ".pgdata")))
    data_dir.mkdir(parents=True, exist_ok=True)
    print(f"[startup] starting embedded Postgres in {data_dir}", flush=True)
    server = pgserver.get_server(data_dir, cleanup_mode="stop")
    # Inherited by the migration, seed and ingest subprocesses, and read by
    # Settings in this process: DATABASE_URL replaces the POSTGRES_* parts.
    os.environ["DATABASE_URL"] = server.get_uri()
    return server


def prepare_database() -> None:
    print("[startup] applying migrations", flush=True)
    _run("-m", "alembic", "upgrade", "head", attempts=6)
    print("[startup] seeding demo users", flush=True)
    _run("-m", "scripts.seed_users")
    print("[startup] ingesting the corpus (unchanged documents are skipped)", flush=True)
    _run("-m", "scripts.ingest_corpus")


def build_ui():  # type: ignore[no-untyped-def]
    import gradio as gr

    from app.web import demo_ui

    def visitor(request: gr.Request) -> str:
        peer = request.client.host if request.client else None
        return demo_ui.client_key(dict(request.headers), peer)

    def on_ask(persona: str, question: str, request: gr.Request) -> tuple[str, str, str]:
        result = demo_ui.ask(persona, question, visitor(request))
        return result.answer, result.sources, result.trace

    def on_search(persona: str, question: str, request: gr.Request) -> tuple[str, str, str]:
        result = demo_ui.search(persona, question, visitor(request))
        return result.answer, result.sources, result.trace

    repo = os.environ.get("DEMO_REPO_URL", "https://github.com/arjunreddy0729/enterpriseiq")

    with gr.Blocks(title="EnterpriseIQ demo") as ui:
        gr.Markdown(
            "# EnterpriseIQ\n"
            "A permission-aware AI assistant for company documents. Every claim in an "
            "answer cites its source, it says so when the documents don't contain the "
            "answer, and nobody can retrieve a document they aren't allowed to read.\n\n"
            '**Try this:** ask *"What are the bonus targets by level?"* as **Marcus (HR)**, '
            "then ask the same thing as **Priya (Engineering)**.\n\n"
            "The company, Northwind Systems, and all 22 documents are fictional. "
            f"[Source code and design notes]({repo}) · [API console](/docs)"
        )
        with gr.Row():
            with gr.Column(scale=2):
                persona = gr.Radio(
                    choices=list(demo_ui.PERSONAS),
                    value=next(iter(demo_ui.PERSONAS)),
                    label="Ask as",
                )
                question = gr.Textbox(
                    label="Question", value=demo_ui.EXAMPLE_QUESTIONS[0], lines=2, max_lines=4
                )
                gr.Examples(
                    examples=[[q] for q in demo_ui.EXAMPLE_QUESTIONS],
                    inputs=[question],
                    label="Examples",
                )
                with gr.Row():
                    ask_button = gr.Button("Ask (AI answer)", variant="primary")
                    search_button = gr.Button("Search only (free)")
            with gr.Column(scale=3):
                answer = gr.Markdown("_Pick a person, then ask._")
                with gr.Accordion("Sources", open=True):
                    sources = gr.Markdown()
                with gr.Accordion("What happened under the hood", open=False):
                    trace = gr.Markdown()
        gr.Markdown(
            "AI answers use Claude and are capped at a small daily budget; when it runs out, "
            "search still works and answers resume at 00:00 UTC. Requests are rate-limited "
            "per visitor. Questions are kept in the request log (that is how the audit trail "
            "works), so please don't type anything personal."
        )

        outputs = [answer, sources, trace]
        ask_button.click(on_ask, [persona, question], outputs, concurrency_limit=2)
        search_button.click(on_search, [persona, question], outputs, concurrency_limit=4)
        question.submit(on_search, [persona, question], outputs, concurrency_limit=4)

    return ui


def main() -> None:
    # Kept referenced for the life of the process; the server stops on exit.
    database = start_embedded_postgres()  # noqa: F841
    prepare_database()

    import gradio as gr
    import uvicorn

    from app.main import create_app
    from app.retrieval.embedder import get_embedder

    # Load the embedding model now, so the first visitor does not wait for it.
    get_embedder().embed_query("warm up")

    app = gr.mount_gradio_app(create_app(), build_ui(), path="/demo")
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "7860")))


if __name__ == "__main__":
    main()
